#!/bin/sh
for i in scripts/*;
    do
    j=$(basename $i)
    echo $j
    help2man $i --no-discard-stderr -N -n $j  -s1 -S PyFAI >man/$j.1
    man -t man/$j.1 | ps2pdf - man/$j.pdf
    man2html man/$j.1 > man/$j.html
    pandoc man/$j.html -o man/$j.rst
    done