.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.38.2.
.TH PYFAI-INTEGRATE "1" "June 2013" "ESRF" "User Commands"
.SH NAME
pyFAI-integrate \- Azimuthal integration GUI
.SH SYNOPSIS
.B pyFAI-integrate
[\fIoptions\fR] \fIfile1.edf file2.edf \fR...
.SH DESCRIPTION
pyFAI\-integrate is a graphical interface (based on Qt) for configuring and
perfroming 1D and 2D azimuthal integration both for SAXS and WAXS on many files.
Both SAXS and WAXS scripts of pyFAI will be replaced (in the future) by this
common interface.
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
switch to verbose/debug mode
