#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    Project: Azimuthal integration
#             https://forge.epn-campus.eu/projects/azimuthal
#
#    File: "$Id$"
#
#    Copyright (C) European Synchrotron Radiation Facility, Grenoble, France
#
#    Principal author:       Jérôme Kieffer (Jerome.Kieffer@ESRF.eu)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
check_calib

This is a very simple tool that checks a calibratation at the sub-pixel level

"""

__author__ = "Jerome Kieffer"
__contact__ = "Jerome.Kieffer@ESRF.eu"
__license__ = "GPLv3+"
__copyright__ = "European Synchrotron Radiation Facility, Grenoble, France"
__date__ = "27/05/2014"
__satus__ = "production"

import pyFAI, pyFAI.calibration
import pylab
import logging
logger = logging.getLogger("check_calib")

from pyFAI.calibration import  CheckCalib


cc = None
if __name__ == "__main__":
    cc = CheckCalib()
    cc.parse()
    cc.integrate()
    cc.rebuild()
    pylab.ion()
    fig = pylab.figure()
    ax1 = fig.add_subplot(2, 2, 3)
    ax1.imshow(cc.delta, aspect="auto", interpolation="nearest", origin="bottom")
    ax1.set_title("Difference image")
    ax2 = fig.add_subplot(2, 2, 1)
    ax2.imshow(cc.masked_image, aspect="auto", interpolation="nearest", origin="bottom")
    ax2.set_title("Raw image")
    ax3 = fig.add_subplot(2, 2, 2)
    ax3.imshow(cc.masked_resynth, aspect="auto", interpolation="nearest", origin="bottom")
    ax3.set_title("Rebuild image")
    ax4 = fig.add_subplot(2, 2, 4)
    ax4.plot(cc.r, cc.I)
    ax4.set_title("powder pattern")
    ax4.set_xlabel(r"2$\theta$ ($^o$)")
    ax4.set_ylabel("Intensity")
    raw_input("enter to quit")
