#!/usr/bin/env python
import sys, os
import  PyQt4

from PyQt4.QtCore import *
from PyQt4.QtGui import *



import PyMca
from PyMca import MaskImageWidget
import fabio

filename = sys.argv[1]

qapp = QApplication(sys.argv)
w = PyMca.MaskImageWidget.MaskImageWidget()
e = fabio.open(filename).data
w.setImageData(e)
w.show()

finished = raw_input("Press enter when you are finished")
m = w.getSelectionMask()
outfile = os.path.splitext(filename)[0] + "-mask.edf"
fabio.edfimage.edfimage(data=m).write(outfile)
