#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    Project: Azimuthal integration
#             https://forge.epn-campus.eu/projects/azimuthal
#
#    File: "$Id$"
#
#    Copyright (C) European Synchrotron Radiation Facility, Grenoble, France
#
#    Authors: Jérôme Kieffer <Jerome.Kieffer@ESRF.eu>
#             Picca Frédéric-Emmanuel <picca@synchrotron-soleil.fr>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""
saxs_integrate is the Saxs script of pyFAI that allows data reduction
for Small Angle Scattering.
"""
__author__ = "Jerome Kieffer, Picca Frédéric-Emmanuel"
__contact__ = "Jerome.Kieffer@ESRF.eu"
__license__ = "GPLv3+"
__copyright__ = "European Synchrotron Radiation Facility, Grenoble, France"
__date__ = "30/11/2011"

import os
import time
import fabio
import pyFAI

from optparse import OptionParser


def main():
    usage = "usage: %prog [options] file1.edf file2.edf ..."
    version = "%prog " + pyFAI.version
    parser = OptionParser(usage=usage, version=version)
    parser.add_option("-p", dest="ponifile",
                      type='string', default=None,
                      help="PyFAI parameter file (.poni)")
    parser.add_option("-w", "--wavelength", dest="wavelength",
                      type="float", default=None,
                      help="wavelength (in meter)")
    parser.add_option("-u", "--dummy", dest="dummy",
                      type="float", default=None,
                      help="dummy value for dead pixels")
    parser.add_option("-U", "--delta_dummy", dest="delta_dummy",
                      type="float", default=None,
                      help="delta dummy value")
    parser.add_option("-m", "--mask", dest="mask",
                      type="string", default=None,
                      help="name of the file containing the mask")
    parser.add_option("-d", "--dark", dest="dark",
                      type="string", default=None,
                      help="name of the file containing the dark")
    parser.add_option("-f", "--flat", dest="flat",
                      type="string", default=None,
                      help="name of the file containing the flat field")
    parser.add_option("-b", "--background", dest="background",
                      type="string", default=None,
                      help="name of the file containing the background")

    (options, args) = parser.parse_args()
    if len(args) != 1:
        parser.error("incorrect number of arguments")

    processFile = [param for param in args if os.path.isfile(param)]

    if options.ponifile and processFile:
        integrator = pyFAI.AzimuthalIntegrator()
        integrator.load(options.ponifile)
        if options.wavelength:
            integrator.wavelength = options.wavelength
        print integrator
        mask = None
        if integrator.maskfile:
            if options.mask:  # override with the command line mask
                integrator.maskfile = options.mask
            fabiomask = fabio.open(integrator.maskfile)
            if isinstance(fabiomask, fabio.fit2dmaskimage.fit2dmaskimage):
                mask = 1 - fabiomask.data
            else:
                mask = fabiomask.data

        for oneFile in processFile:
            t0 = time.time()
            fabioFile = fabio.open(oneFile)
            outFile = os.path.splitext(oneFile)[0] + ".dat"
            if fabioFile.nframes > 1:
                integrator.saxs(data=fabioFile.data,
                                nbPt=min(fabioFile.data.shape),
                                dummy=options.dummy,
                                delta_dummy=options.delta_dummy,
                                filename=outFile,
                                mask=mask,
                                variance=fabioFile.next().data,
                                method="BBox")
            else:
                integrator.saxs(data=fabioFile.data,
                                nbPt=min(fabioFile.data.shape),
                                dummy=options.dummy,
                                delta_dummy=options.delta_dummy,
                                filename=outFile,
                                mask=mask,
                                method="BBox")
            t1 = time.time()

            print("Integration took %6.3fs %s --> %s" %
                  (t1 - t0, oneFile, outFile))

if __name__ == "__main__":
    main()
