#!/bin/bash

# Setup jupyter bash kernel
python -m bash_kernel.install

# Download resources
RESOURCES_URL="http://www.silx.org/pub/pyFAI"
echo "Download notebooks from ${RESOURCES_URL}"

COOKBOOK_DIR="doc/source/usage/cookbook"
COOKBOOK_FILES="LaB6_29.4keV.tif
LaB6_29.4keV.poni
F_K4320T_Cam43_30012013_distorsion.spline"

for FILE in ${COOKBOOK_FILES}; do
    URL="${RESOURCES_URL}/cookbook/calibration/${FILE}";
    echo "Download ${URL}";
    wget "${URL}" -O ${COOKBOOK_DIR}/${FILE};
done
